name: buy_rent_used_clothes
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  provider:
  freezed: ^2.0.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  url_launcher: ^6.1.2


dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
    enabled: true